// Hanjing Clinic Mini-Program UI Page Data
// Auto-generated by parse_pages.py (Lightweight Metadata version)

const HJ_UI_CATEGORIES = [
  "首页及基础 (Main & Base)",
  "就诊与预约 (Clinic Booking)",
  "量表与评估 (Assessments)",
  "治疗与调理 (Treatment & Wear)",
  "商城与分销 (Mall & Affiliates)",
  "社区与内容 (Forum & Live)",
  "设置与个人 (Settings & Profiles)"
];

const HJ_UI_PAGES = [
  {
    "id": "phone-1",
    "path": "pages/index/index",
    "title": "鼾静健康诊所",
    "category": "首页及基础 (Main & Base)",
    "screenClass": "page-pages-index-index"
  },
  {
    "id": "phone-2",
    "path": "pages/appointment/index",
    "title": "预约挂号",
    "category": "就诊与预约 (Clinic Booking)",
    "screenClass": "page-pages-appointment-index"
  },
  {
    "id": "phone-3",
    "path": "pages/assessment/index",
    "title": "睡眠评估",
    "category": "量表与评估 (Assessments)",
    "screenClass": "page-pages-assessment-index"
  },
  {
    "id": "phone-4",
    "path": "pages/treatment/index",
    "title": "治疗追踪",
    "category": "治疗与调理 (Treatment & Wear)",
    "screenClass": "page-pages-treatment-index"
  },
  {
    "id": "phone-5",
    "path": "pages/product/index",
    "title": "健康商城",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-product-index"
  },
  {
    "id": "phone-6",
    "path": "pages/profile/index",
    "title": "我的",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-index"
  },
  {
    "id": "phone-7",
    "path": "pages/auth/login",
    "title": "微信授权登录",
    "category": "首页及基础 (Main & Base)",
    "screenClass": "page-pages-auth-login"
  },
  {
    "id": "phone-8",
    "path": "pages/appointment/store-select",
    "title": "选择门店",
    "category": "就诊与预约 (Clinic Booking)",
    "screenClass": "page-pages-appointment-store-select"
  },
  {
    "id": "phone-9",
    "path": "pages/appointment/doctor-detail",
    "title": "医生详情",
    "category": "就诊与预约 (Clinic Booking)",
    "screenClass": "page-pages-appointment-doctor-detail"
  },
  {
    "id": "phone-10",
    "path": "pages/appointment/time-select",
    "title": "选择时段",
    "category": "就诊与预约 (Clinic Booking)",
    "screenClass": "page-pages-appointment-time-select"
  },
  {
    "id": "phone-11",
    "path": "pages/appointment/confirm",
    "title": "预约确认",
    "category": "就诊与预约 (Clinic Booking)",
    "screenClass": "page-pages-appointment-confirm"
  },
  {
    "id": "phone-12",
    "path": "pages/appointment/success",
    "title": "预约成功",
    "category": "就诊与预约 (Clinic Booking)",
    "screenClass": "page-pages-appointment-success"
  },
  {
    "id": "phone-13",
    "path": "pages/appointment/detail",
    "title": "预约详情",
    "category": "就诊与预约 (Clinic Booking)",
    "screenClass": "page-pages-appointment-detail"
  },
  {
    "id": "phone-14",
    "path": "pages/appointment/reschedule",
    "title": "改约",
    "category": "就诊与预约 (Clinic Booking)",
    "screenClass": "page-pages-appointment-reschedule"
  },
  {
    "id": "phone-15",
    "path": "pages/assessment/questionnaire/index",
    "title": "ESS嗜睡量表",
    "category": "量表与评估 (Assessments)",
    "screenClass": "page-pages-assessment-questionnaire-index"
  },
  {
    "id": "phone-16",
    "path": "pages/assessment/result/index",
    "title": "评估结果",
    "category": "量表与评估 (Assessments)",
    "screenClass": "page-pages-assessment-result-index"
  },
  {
    "id": "phone-17",
    "path": "pages/assessment/recording/index",
    "title": "AI鼾声分析",
    "category": "量表与评估 (Assessments)",
    "screenClass": "page-pages-assessment-recording-index"
  },
  {
    "id": "phone-18",
    "path": "pages/assessment/snore-result/index",
    "title": "鼾声分析报告",
    "category": "量表与评估 (Assessments)",
    "screenClass": "page-pages-assessment-snore-result-index"
  },
  {
    "id": "phone-19",
    "path": "pages/treatment/sleep-trend/index",
    "title": "睡眠趋势",
    "category": "治疗与调理 (Treatment & Wear)",
    "screenClass": "page-pages-treatment-sleep-trend-index"
  },
  {
    "id": "phone-20",
    "path": "pages/treatment/timeline/index",
    "title": "治疗时间线",
    "category": "治疗与调理 (Treatment & Wear)",
    "screenClass": "page-pages-treatment-timeline-index"
  },
  {
    "id": "phone-21",
    "path": "pages/treatment/doctor-advice/index",
    "title": "医嘱建议",
    "category": "治疗与调理 (Treatment & Wear)",
    "screenClass": "page-pages-treatment-doctor-advice-index"
  },
  {
    "id": "phone-22",
    "path": "pages/treatment/adjust-detail/index",
    "title": "设备调整",
    "category": "治疗与调理 (Treatment & Wear)",
    "screenClass": "page-pages-treatment-adjust-detail-index"
  },
  {
    "id": "phone-23",
    "path": "pages/treatment/sleep-report/index",
    "title": "睡眠报告",
    "category": "治疗与调理 (Treatment & Wear)",
    "screenClass": "page-pages-treatment-sleep-report-index"
  },
  {
    "id": "phone-24",
    "path": "pages/product/detail/index",
    "title": "商品详情",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-product-detail-index"
  },
  {
    "id": "phone-25",
    "path": "pages/product/detail",
    "title": "商品详情",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-product-detail"
  },
  {
    "id": "phone-26",
    "path": "pages/profile/medical-records/index",
    "title": "病历档案",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-medical-records-index"
  },
  {
    "id": "phone-27",
    "path": "pages/profile/device-manage/index",
    "title": "阻鼾器管理",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-device-manage-index"
  },
  {
    "id": "phone-28",
    "path": "pages/profile/device-manage/wearing-data/index",
    "title": "佩戴数据",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-device-manage-wearing-data-index"
  },
  {
    "id": "phone-29",
    "path": "pages/profile/device-manage/maintenance/index",
    "title": "维护记录",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-device-manage-maintenance-index"
  },
  {
    "id": "phone-30",
    "path": "pages/profile/device-manage/feedback/index",
    "title": "使用反馈",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-device-manage-feedback-index"
  },
  {
    "id": "phone-31",
    "path": "pages/profile/family-members/index",
    "title": "家庭成员",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-family-members-index"
  },
  {
    "id": "phone-32",
    "path": "pages/profile/family-members/add-member/index",
    "title": "添加成员",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-family-members-add-member-index"
  },
  {
    "id": "phone-33",
    "path": "pages/profile/member-benefits/index",
    "title": "会员权益",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-member-benefits-index"
  },
  {
    "id": "phone-34",
    "path": "pages/profile/settings/index",
    "title": "设置",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-settings-index"
  },
  {
    "id": "phone-35",
    "path": "pages/profile/settings/personal-info/index",
    "title": "个人信息",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-settings-personal-info-index"
  },
  {
    "id": "phone-36",
    "path": "pages/profile/settings/account-security/index",
    "title": "账号安全",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-settings-account-security-index"
  },
  {
    "id": "phone-37",
    "path": "pages/profile/notifications/index",
    "title": "消息通知",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-notifications-index"
  },
  {
    "id": "phone-38",
    "path": "pages/profile/online-service/index",
    "title": "在线客服",
    "category": "设置与个人 (Settings & Profiles)",
    "screenClass": "page-pages-profile-online-service-index"
  },
  {
    "id": "phone-39",
    "path": "pages/order/index",
    "title": "我的订单",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-order-index"
  },
  {
    "id": "phone-40",
    "path": "pages/order/detail",
    "title": "订单详情",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-order-detail"
  },
  {
    "id": "phone-41",
    "path": "pages/distribution/center/index",
    "title": "分销中心",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-distribution-center-index"
  },
  {
    "id": "phone-42",
    "path": "pages/distribution/commission/index",
    "title": "佣金明细",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-distribution-commission-index"
  },
  {
    "id": "phone-43",
    "path": "pages/distribution/withdraw/index",
    "title": "提现申请",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-distribution-withdraw-index"
  },
  {
    "id": "phone-44",
    "path": "pages/distribution/withdraw-records/index",
    "title": "提现记录",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-distribution-withdraw-records-index"
  },
  {
    "id": "phone-45",
    "path": "pages/distribution/team/index",
    "title": "团队成员",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-distribution-team-index"
  },
  {
    "id": "phone-46",
    "path": "pages/distribution/invite/index",
    "title": "邀请好友",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-distribution-invite-index"
  },
  {
    "id": "phone-47",
    "path": "pages/distribution/products/index",
    "title": "推广商品",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-distribution-products-index"
  },
  {
    "id": "phone-48",
    "path": "pages/distribution/rules/index",
    "title": "分销规则",
    "category": "商城与分销 (Mall & Affiliates)",
    "screenClass": "page-pages-distribution-rules-index"
  },
  {
    "id": "phone-49",
    "path": "pages/live/list/index",
    "title": "直播中心",
    "category": "社区与内容 (Forum & Live)",
    "screenClass": "page-pages-live-list-index"
  },
  {
    "id": "phone-50",
    "path": "pages/live/playback/index",
    "title": "直播回放",
    "category": "社区与内容 (Forum & Live)",
    "screenClass": "page-pages-live-playback-index"
  },
  {
    "id": "phone-51",
    "path": "pages/community/index",
    "title": "医患社区",
    "category": "社区与内容 (Forum & Live)",
    "screenClass": "page-pages-community-index"
  },
  {
    "id": "phone-52",
    "path": "pages/community/detail/index",
    "title": "帖子详情",
    "category": "社区与内容 (Forum & Live)",
    "screenClass": "page-pages-community-detail-index"
  },
  {
    "id": "phone-53",
    "path": "pages/community/publish/index",
    "title": "发帖",
    "category": "社区与内容 (Forum & Live)",
    "screenClass": "page-pages-community-publish-index"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { HJ_UI_CATEGORIES, HJ_UI_PAGES };
}
